CREATE DOMAIN token_id AS TEXT CHECK (VALUE ~ '^tok_[0-9a-v]{20}$');

CREATE TABLE IF NOT EXISTS token_ (
    id token_id PRIMARY KEY,
    hash BYTEA UNIQUE,
    user_id user_id NOT NULL REFERENCES user_ (id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    accessed_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMP(0) WITH TIME ZONE,
    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    version INTEGER NOT NULL DEFAULT 1
);
