name: Run Tests

on: workflow_call

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.23.1"

      - name: Download Encore CLI
        uses: sozo-design/curl@v1.0.2
        with:
          args: --output install.sh -L https://encore.dev/install.sh

      - name: Install Encore CLI
        run: bash install.sh

      - name: Download Dependencies
        run: go mod download -x

      - name: Encore Check
        run: CGO_ENABLED=0 /home/runner/.encore/bin/encore check --verbose

      - name: Test
        run: CGO_ENABLED=0 go test ./...

      - name: Run Vet
        run: CGO_ENABLED=0 go vet ./...
